name: Deploy to Firebase

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: cd functions && npm install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          action: deploy
          project_id: 'aventuria-baeba'
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
